import itertools
import pyrage
from pyrage import passphrase
from multiprocessing import Pool
with open("secret.age", 'rb') as f:        
    bFileText = f.read()
        
possible_combos = [['was', 'chosen', 'giving', 'enter', 'standard'],
 ['war', 'given', 'had', 'consist', 'sent', 'danger'],
 ['war', 'given', 'consist', 'grant', 'ended', 'has'],
 ['war', 'given', 'consist', 'granted', 'end', 'has'],
 ['war', 'chosen', 'granting', 'and', 'vested', 'is'],
 ['water', 'given', 'consist', 'end', 'grand', 'has'],
 ['water', 'chosen', 'iv', 'and', 'signed', 'grants'],
 ['water', 'chosen', 'and', 'signed', 'vi', 'grants'],
 ['drawn', 'given', 'in', 'had', 'state', 'congress'],
 ['drawn', 'given', 'intents', 'as', 'charged', 'so'],
 ['drawn', 'net', 'consist', 'has', 'danger', 'give'],
 ['drawn', 'ten', 'consist', 'has', 'danger', 'give'],
 ['drawn', 'chosen', 'granting', 'as', 'i', 'vested'],
 ['drawn', 'chosen', 'granting', 'vested', 'is', 'a'],
 ['drawn', 'chosen', 'in', 'grand', 'states', 'give'],
 ['drawn', 'chosen', 'state', 'sign', 'iv', 'danger'],
 ['drawn', 'chosen', 'state', 'sign', 'vi', 'danger'],
 ['drawn', 'chosen', 'sign', 'iv', 'and', 'greatest'],
 ['drawn', 'chosen', 'sign', 'iv', 'granted', 'seat'],
 ['drawn', 'chosen', 'sign', 'and', 'vi', 'greatest'],
 ['drawn', 'chosen', 'sign', 'vi', 'granted', 'seat'],
 ['drawn', 'chosen', 'iv', 'signed', 'grant', 'seat'],
 ['drawn', 'chosen', 'and', 'giving', 'states', 're'],
 ['drawn', 'chosen', 'signed', 'vi', 'grant', 'seat'],
 ['what', 'seven', 'consist', 'i', 'grand', 'danger'],
 ['was', 'given', 'had', 'consist', 'enter', 'grand'],
 ['was', 'chosen', 'denied', 'iv', 'grants', 'grant'],
 ['was', 'chosen', 'denied', 'vi', 'grants', 'grant'],
 ['war', 'given', 'consent', 'had', 's', 'granted', 'is'],
 ['war', 'given', 'consent', 'had', 's', 'its', 'danger'],
 ['war', 'given', 'consent', 'granted', 'd', 'has', 'is'],
 ['war', 'given', 'consent', 'its', 'd', 'has', 'danger'],
 ['war', 'given', 'in', 'had', 'and', 'congress', 'test'],
 ['war', 'given', 'it', 'had', 'and', 'sent', 'congress'],
 ['war', 'given', 'had', 'intents', 'congress', 'd', 'a'],
 ['war', 'given', 'and', 'intents', 'charged', 's', 'so'],
 ['war', 'net', 'consist', 'end', 'grand', 'has', 'give'],
 ['war', 'ten', 'consist', 'end', 'grand', 'has', 'give'],
 ['war', 'chosen', 'granting', 'seats', 'iv', 'end', 'd'],
 ['war', 'chosen', 'granting', 'seats', 'vi', 'end', 'd'],
 ['war', 'chosen', 'granting', 'in', 'as', 'vested', 'd'],
 ['war', 'chosen', 'granting', 'and', 'i', 'vested', 's'],
 ['war', 'chosen', 'granting', 'as', 'its', 'ended', 'v'],
 ['war', 'chosen', 'granting', 'vested', 'd', 'an', 'is'],
 ['war', 'chosen', 'in', 'state', 'signed', 'grand', 'v'],
 ['war', 'chosen', 'in', 'sign', 'vested', 'at', 'grand'],
 ['war', 'chosen', 'in', 'sign', 'vest', 'grand', 'date'],
 ['war', 'chosen', 'in', 'sign', 'v', 'danger', 'stated'],
 ['war', 'chosen', 'in', 'signed', 'grants', 'v', 'date'],
 ['war', 'chosen', 'in', 'signed', 'at', 'vest', 'grand'],
 ['war', 'chosen', 'it', 'sign', 'and', 'vest', 'danger'],
 ['war', 'chosen', 'it', 'sign', 'vested', 'grand', 'an'],
 ['war', 'chosen', 'it', 'signed', 'vest', 'grand', 'an'],
 ['war', 'chosen', 'state', 'sign', 'iv', 'end', 'grand'],
 ['war', 'chosen', 'state', 'sign', 'vi', 'end', 'grand'],
 ['war', 'chosen', 'denied', 'sign', 'grants', 'at', 'v'],
 ['war', 'chosen', 'sign', 'iv', 'and', 'danger', 'test'],
 ['war', 'chosen', 'sign', 'iv', 'grants', 'at', 'ended'],
 ['war', 'chosen', 'sign', 'iv', 'grants', 'end', 'date'],
 ['war', 'chosen', 'sign', 'iv', 'sent', 'grand', 'date'],
 ['war', 'chosen', 'sign', 'and', 'vi', 'danger', 'test'],
 ['war', 'chosen', 'sign', 'and', 'i', 'vested', 'grant'],
 ['war', 'chosen', 'sign', 'and', 'i', 'granted', 'vest'],
 ['war', 'chosen', 'sign', 'vi', 'grants', 'at', 'ended'],
 ['war', 'chosen', 'sign', 'vi', 'grants', 'end', 'date'],
 ['war', 'chosen', 'sign', 'vi', 'sent', 'grand', 'date'],
 ['war', 'chosen', 'iv', 'signed', 'grants', 'at', 'end'],
 ['war', 'chosen', 'iv', 'signed', 'sent', 'at', 'grand'],
 ['war', 'chosen', 'iv', 'signed', 'grand', 'an', 'test'],
 ['war', 'chosen', 'and', 'signed', 'i', 'grant', 'vest'],
 ['war', 'chosen', 'and', 'grants', 'its', 'end', 'give'],
 ['war', 'chosen', 'and', 'sent', 'its', 'grand', 'give'],
 ['war', 'chosen', 'intents', 'as', 'd', 'grand', 'give'],
 ['war', 'chosen', 'signed', 'vi', 'grants', 'at', 'end'],
 ['war', 'chosen', 'signed', 'vi', 'sent', 'at', 'grand'],
 ['war', 'chosen', 'signed', 'vi', 'grand', 'an', 'test'],
 ['war', 'chosen', 'signed', 'granted', 'its', 'an', 'v'],
 ['water', 'given', 'consent', 'had', 's', 'grand', 'is'],
 ['water', 'given', 'consent', 'd', 'grand', 'has', 'is'],
 ['water', 'net', 'had', 'sign', 'iv', 'and', 'congress'],
 ['water', 'net', 'had', 'sign', 'and', 'vi', 'congress'],
 ['water', 'ten', 'had', 'sign', 'iv', 'and', 'congress'],
 ['water', 'ten', 'had', 'sign', 'and', 'vi', 'congress'],
 ['water', 'chosen', 'sign', 'iv', 'and', 's', 'granted'],
 ['water', 'chosen', 'sign', 'and', 'vi', 's', 'granted'],
 ['water', 'chosen', 'sign', 'and', 'i', 'vest', 'grand'],
 ['water', 'chosen', 'sign', 'and', 'granted', 'v', 'is'],
 ['water', 'chosen', 'sign', 'and', 'its', 'v', 'danger'],
 ['water', 'chosen', 'iv', 'and', 'signed', 'grant', 's'],
 ['water', 'chosen', 'iv', 'signed', 'grants', 'd', 'an'],
 ['water', 'chosen', 'and', 'signed', 'vi', 'grant', 's'],
 ['water', 'chosen', 'and', 'signed', 'grants', 'i', 'v'],
 ['water', 'chosen', 'and', 'signed', 'grant', 'v', 'is'],
 ['water', 'chosen', 'signed', 'vi', 'grants', 'd', 'an'],
 ['water', 'chosen', 'signed', 'its', 'grand', 'an', 'v'],
 ['drawn', 'given', 'no', 'in', 'charged', 's', 'states'],
 ['drawn', 'given', 'no', 'as', 'charged', 'sent', 'its'],
 ['drawn', 'given', 'in', 'had', 'congress', 'test', 'a'],
 ['drawn', 'given', 'in', 'charged', 's', 'states', 'on'],
 ['drawn', 'given', 'it', 'had', 'sent', 'congress', 'a'],
 ['drawn', 'given', 'it', 'congress', 'at', 'end', 'has'],
 ['drawn', 'given', 'had', 'i', 'sent', 'congress', 'at'],
 ['drawn', 'given', 'had', 'i', 'congress', 'an', 'test'],
 ['drawn', 'given', 'intents', 'charged', 's', 'so', 'a'],
 ['drawn', 'given', 'as', 'charged', 'sent', 'its', 'on'],
 ['drawn', 'given', 'charged', 'sent', 'its', 'an', 'so'],
 ['drawn', 'seven', 'no', 'sign', 'charged', 'its', 'at'],
 ['drawn', 'seven', 'sign', 'charged', 'its', 'at', 'on'],
 ['drawn', 'net', 'no', 'seats', 'sign', 'iv', 'charged'],
 ['drawn', 'net', 'no', 'seats', 'sign', 'vi', 'charged'],
 ['drawn', 'net', 'seats', 'sign', 'iv', 'charged', 'on'],
 ['drawn', 'net', 'seats', 'sign', 'vi', 'charged', 'on'],
 ['drawn', 'net', 'it', 'and', 'congress', 'has', 'give'],
 ['drawn', 'net', 'had', 'congress', 'its', 'an', 'give'],
 ['drawn', 'ten', 'no', 'seats', 'sign', 'iv', 'charged'],
 ['drawn', 'ten', 'no', 'seats', 'sign', 'vi', 'charged'],
 ['drawn', 'ten', 'seats', 'sign', 'iv', 'charged', 'on'],
 ['drawn', 'ten', 'seats', 'sign', 'vi', 'charged', 'on'],
 ['drawn', 'ten', 'it', 'and', 'congress', 'has', 'give'],
 ['drawn', 'ten', 'had', 'congress', 'its', 'an', 'give'],
 ['drawn', 'chosen', 'tender', 'as', 'giving', 's', 'at'],
 ['drawn', 'chosen', 'granting', 'i', 'vested', 's', 'a'],
 ['drawn', 'chosen', 'seats', 'in', 'grant', 'd', 'give'],
 ['drawn', 'chosen', 'in', 'state', 's', 'grand', 'give'],
 ['drawn', 'chosen', 'in', 'as', 'grand', 'test', 'give'],
 ['drawn', 'chosen', 'in', 'grants', 's', 'give', 'date'],
 ['drawn', 'chosen', 'in', 'grants', 'd', 'seat', 'give'],
 ['drawn', 'chosen', 'it', 'sign', 'vest', 'danger', 'a'],
 ['drawn', 'chosen', 'it', 'sign', 'v', 'seat', 'danger'],
 ['drawn', 'chosen', 'it', 'as', 'grants', 'end', 'give'],
 ['drawn', 'chosen', 'it', 'as', 'sent', 'grand', 'give'],
 ['drawn', 'chosen', 'state', 'sign', 'i', 'v', 'danger'],
 ['drawn', 'chosen', 'state', 'and', 'giving', 's', 're'],
 ['drawn', 'chosen', 'are', 'and', 'giving', 's', 'test'],
 ['drawn', 'chosen', 'sign', 'iv', 'greatest', 'd', 'an'],
 ['drawn', 'chosen', 'sign', 'iv', 'danger', 'test', 'a'],
 ['drawn', 'chosen', 'sign', 'and', 'i', 'greatest', 'v'],
 ['drawn', 'chosen', 'sign', 'vi', 'greatest', 'd', 'an'],
 ['drawn', 'chosen', 'sign', 'vi', 'danger', 'test', 'a'],
 ['drawn', 'chosen', 'sign', 'i', 'vested', 'grant', 'a'],
 ['drawn', 'chosen', 'sign', 'i', 'granted', 'vest', 'a'],
 ['drawn', 'chosen', 'sign', 'i', 'granted', 'v', 'seat'],
 ['drawn', 'chosen', 'sign', 'i', 'at', 'vest', 'danger'],
 ['drawn', 'chosen', 'and', 'as', 'giving', 'test', 're'],
 ['drawn', 'chosen', 'signed', 'i', 'grant', 'vest', 'a'],
 ['drawn', 'chosen', 'signed', 'i', 'grant', 'v', 'seat'],
 ['drawn', 'chosen', 'as', 'grant', 'its', 'end', 'give'],
 ['drawn', 'chosen', 'grants', 'its', 'end', 'a', 'give'],
 ['drawn', 'chosen', 'grants', 'at', 'end', 'is', 'give'],
 ['drawn', 'chosen', 'giving', 's', 'an', 'stated', 're'],
 ['drawn', 'chosen', 'giving', 'd', 'an', 'states', 're'],
 ['drawn', 'chosen', 's', 'granted', 'its', 'an', 'give'],
 ['drawn', 'chosen', 'sent', 'its', 'grand', 'a', 'give'],
 ['drawn', 'chosen', 'sent', 'at', 'grand', 'is', 'give'],
 ['drawn', 'chosen', 'grand', 'an', 'is', 'test', 'give'],
 ['who', 'encreased', 'granting', 'and', 's', 'its', 'v'],
 ['who', 'encreased', 'it', 'sign', 'and', 'grants', 'v'],
 ['who', 'encreased', 'sign', 'and', 'grant', 'its', 'v'],
 ['what', 'given', 'consent', 's', 'd', 'raise', 'grand'],
 ['what', 'given', 'are', 'consist', 's', 'end', 'grand'],
 ['what', 'given', 'and', 'consist', 's', 'danger', 're'],
 ['what', 'given', 'consist', 'as', 'end', 'grand', 're'],
 ['what', 'encreased', 'do', 'in', 'sign', 'grants', 'v'],
 ['what', 'encreased', 'no', 'sign', 'iv', 'grants', 'd'],
 ['what', 'encreased', 'no', 'sign', 'vi', 'grants', 'd'],
 ['what', 'encreased', 'no', 'sign', 'its', 'grand', 'v'],
 ['what', 'encreased', 'sign', 'iv', 'grants', 'd', 'on'],
 ['what', 'encreased', 'sign', 'vi', 'grants', 'd', 'on'],
 ['what', 'encreased', 'sign', 'its', 'grand', 'v', 'on'],
 ['what', 'seven', 'it', 'and', 'i', 'congress', 'grand'],
 ['what', 'net', 'iv', 'and', 'congress', 'is', 'danger'],
 ['what', 'net', 'and', 'vi', 'congress', 'is', 'danger'],
 ['what', 'ten', 'iv', 'and', 'congress', 'is', 'danger'],
 ['what', 'ten', 'and', 'vi', 'congress', 'is', 'danger'],
 ['was', 'given', 'consent', 'had', 'its', 'grand', 're'],
 ['was', 'given', 'had', 'consist', 'grant', 'end', 're'],
 ['was', 'net', 'in', 'had', 'iv', 'congress', 'granted'],
 ['was', 'net', 'in', 'had', 'vi', 'congress', 'granted'],
 ['was', 'ten', 'in', 'had', 'iv', 'congress', 'granted'],
 ['was', 'ten', 'in', 'had', 'vi', 'congress', 'granted'],
 ['was', 'chosen', 'tender', 'granting', 'iv', 'as', 'd'],
 ['was', 'chosen', 'tender', 'granting', 'vi', 'as', 'd'],
 ['was', 'chosen', 'tender', 'sign', 'iv', 'at', 'grand'],
 ['was', 'chosen', 'tender', 'sign', 'vi', 'at', 'grand'],
 ['was', 'chosen', 'granting', 'ever', 'and', 'its', 'd'],
 ['was', 'chosen', 'granting', 's', 'd', 'retained', 'v'],
 ['was', 'chosen', 'in', 'it', 'vest', 'grand', 'danger'],
 ['was', 'chosen', 'in', 'iv', 'grand', 'danger', 'test'],
 ['was', 'chosen', 'in', 'vi', 'grand', 'danger', 'test'],
 ['was', 'chosen', 'in', 'i', 'vested', 'grant', 'grand'],
 ['was', 'chosen', 'in', 'i', 'granted', 'vest', 'grand'],
 ['was', 'chosen', 'in', 'granted', 'its', 'v', 'danger'],
 ['was', 'chosen', 'it', 'iv', 'grants', 'end', 'danger'],
 ['was', 'chosen', 'it', 'iv', 'sent', 'grand', 'danger'],
 ['was', 'chosen', 'it', 'vi', 'grants', 'end', 'danger'],
 ['was', 'chosen', 'it', 'vi', 'sent', 'grand', 'danger'],
 ['was', 'chosen', 'denied', 'grants', 'i', 'grant', 'v'],
 ['was', 'chosen', 'sign', 'grant', 'd', 'retained', 'v'],
 ['was', 'chosen', 'iv', 'grants', 'i', 'grant', 'ended'],
 ['was', 'chosen', 'iv', 'grants', 'i', 'granted', 'end'],
 ['was', 'chosen', 'iv', 'i', 'sent', 'granted', 'grand'],
 ['was', 'chosen', 'iv', 'grant', 'granted', 'end', 'is'],
 ['was', 'chosen', 'iv', 'grant', 'its', 'end', 'danger'],
 ['was', 'chosen', 'vi', 'grants', 'i', 'grant', 'ended'],
 ['was', 'chosen', 'vi', 'grants', 'i', 'granted', 'end'],
 ['was', 'chosen', 'vi', 'i', 'sent', 'granted', 'grand'],
 ['was', 'chosen', 'vi', 'grant', 'granted', 'end', 'is'],
 ['was', 'chosen', 'vi', 'grant', 'its', 'end', 'danger']]

possible_permutations = []
for c in possible_combos:
    possible_permutations += list(itertools.permutations(c))


def decrypt(word):
    try:
        answer =  passphrase.decrypt(bFileText, ''.join(word))
        print('FOUND SOLUTION!!!!', ''.join(word))
        return answer
    except pyrage.DecryptError:
        return False
    

with Pool() as p:
    p.map(decrypt, possible_permutations)
